baseURL = "https://zwebzone.github.io/"
defaultContentLanguage = "en"
languageCode = "en"

title = "zwebrain"

theme = "gokarna"

publishDir = "docs"

# Automatically generate robots.txt
enableRobotsTXT = true

enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[menu]
  

  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "essay"

    url = "/essay/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "随笔"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "note"

    url = "/note/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "笔记"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "publications"
    name = "发表物"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
    # pre = "<span data-feather='tag'></span>"

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5
    # pre = "<span data-feather='smile'></span>"


[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "Is it everything or is it just that I’m insane?"
  
  # Accent color is displayed when you hover over <a> tags
  accentColor = "#66CCFF"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = '''
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?a7e4b05d3f48c8f1563ea8d84d1b667a";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
'''

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "zwebrain"

  socialIcons = [
    {name = "github", url = "https://github.com/zwebzone"},
    {name = "bilibili", url = "https://space.bilibili.com/8519667"},
    # {name = "outlook", url = "mailto:11811721@mail.sustech.edu.cn"},
    {name = "neteasecloudmusic", url="https://y.music.163.com/m/user?id=96064525"},
    {name = "steam", url="https://steamcommunity.com/id/zwebrain"},
    {name = "youtube", url = "https://www.youtube.com/channel/UCSCddBiG0wKSliowiaUaOGg"},
  ]

  metaKeywords = ["blog", "zwebrain"]